// LinUCB.hpp
//
// Contextual linear UCB. Per arm a, maintains:
//   A_a ∈ R^{d×d}, init λI
//   b_a ∈ R^d,     init 0
// Tick:
//   θ_a   = A_a^{-1} b_a
//   s_a   = θ_a^T x + α · sqrt(x^T A_a^{-1} x)
//   a*    = argmax_a s_a   (after action-filter)
// Update on reward r_t for arm a* with context x_t:
//   A_a += x_t x_t^T;   b_a += r_t · x_t
//
// v1 uses a tiny in-tree dense linear solver (Cholesky on the small d×d
// matrix, ~50 LoC), avoiding an Eigen dependency that may not be on the
// Aurora build path. Replace with Eigen later if d grows.

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace aurora_bandit {

class LinUCB {
public:
    LinUCB(int n_arms, int n_features, double alpha = 1.0, double ridge = 1.0);

    // Pure UCB select; returns arm index + writes the chosen ucb score.
    int select(const std::vector<double> &x, double &out_score) const;

    // Update after the reward for the *previous* action lands.
    void update(const std::vector<double> &x, int arm_idx, double reward);

    // Disable an arm permanently (e.g. write-readback assertion failed).
    void disable_arm(int arm_idx);

    // Mark an arm as having violated the runtime-slack budget; the action
    // filter will deprioritize it for the rest of the run.
    void penalize_arm(int arm_idx);

    // JSON warm-start loader: parses (A_a, b_a) for each arm from a
    // priors file generated by analysis/scripts/generate_phase2_priors.py.
    // Returns false on failure; agent then runs cold (A=λI, b=0).
    bool warm_start_from_json(const std::string &path);

    void  set_alpha(double a) { m_alpha = a; }
    double alpha() const { return m_alpha; }
    int   n_arms() const { return m_n_arms; }
    int   n_features() const { return m_d; }

    uint64_t update_count(int arm_idx) const;

private:
    // Per-arm state. A is stored row-major in a flat vector.
    struct ArmState {
        std::vector<double> A;    // d*d
        std::vector<double> b;    // d
        std::vector<double> theta;// d, recomputed lazily
        uint64_t            n_updates = 0;
        bool                disabled = false;
        bool                penalized = false;
        bool                theta_dirty = true;
    };

    void recompute_theta(ArmState &arm) const;
    void cholesky_solve(const std::vector<double> &A, const std::vector<double> &y,
                        std::vector<double> &out) const;
    double quadratic_form_inv(const std::vector<double> &A,
                              const std::vector<double> &x) const;

    int                   m_n_arms;
    int                   m_d;
    double                m_alpha;
    double                m_ridge;
    mutable std::vector<ArmState> m_arms;
};

} // namespace aurora_bandit
